name: Actions workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: checkout
        id: checkout
        uses: actions/checkout@v1
      - name: clone_dbt
        run: |
          git clone git@github.com:rjribeiro/dbt.git dbt
          git checkout $GITHUB_REF
      - name: list files
        run: |
          ls -Ra