name: Actions workflow
on: 
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: checkout
        id: checkout
        uses: actions/checkout@v1
      - name: clone_dbt
        run: |
          echo "${{ github.token }}"
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
      - name: list files
        run: |
          ls -Ra