name: Actions workflow
on: 
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: checkout
        id: checkout
        uses: actions/checkout@v1
      - name: clone_dbt
        run: |
          git clone "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/rjribeiro/dbt.git" dbt
      - name: list files
        run: |
          ls -Ra