name: Actions workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: checkout
        id: checkout
        uses: actions/checkout
      - name: clone_dbt
        run: |
          git clone git@github.com:$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA
      - name: list files
        run: |
          ls -Ra