name: Actions workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      # - name: checkout
      #   id: checkout
      #   uses: actions/checkout@v1
      - name: clone_dbt
        run: |
          echo "${{ github.token }}"
          git clone git@github.com:$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA
      - name: list files
        run: |
          ls -Ra