name: Actions workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: checkout
        id: checkout
        uses: actions/checkout@v1

      - name: list files
        run: |
          pwd
          ls