name: Shell comands
on:
  - push
jobs:
  run-shell-comand:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello world"
      - name: echo multiline
        run: |
          node -v
          npm  -v